Import('env')
Import('rose_lib')

env = env.Clone()

env.Prepend(LIBS=[rose_lib, 'gtest', 'pthread'])

test = env.Program(target='test',
                   source=env.Glob('*.cpp'))

env.Command(target='run-test',
            source=test[0],
            action=test[0].abspath)

# vim:ft=python
