from os import environ, path

Import('env')
Import('rose_lib')

env = env.Clone()

GTEST_DIR = '#external/googletest'

env.Prepend(LIBS=[rose_lib],
            CPPPATH=[Dir(GTEST_DIR),
                     Dir(GTEST_DIR + '/include')])

test = env.Program(target='test',
                   source=[env.Glob('*.cpp'),
                           File(GTEST_DIR + '/src/gtest-all.cc')])

run = env.Command(target='unit-test',
                  source=test[0],
                  action=test[0].abspath)

if ARGUMENTS.get('coverage', 0):
    env.GenHtml(target=Dir('html'),
                source=env.LCov(target='coverage.info',
                                source=run,
                                LCOVDIR='.',
                                LCOVBASEDIR='#/'))

    env.Clean(test,
              [env.Dir('html'),
               env.File('test.gcno')])

# vim:ft=python ts=4 sw=4 sts=4 et
