Import('env', 'rose_lib')

env = env.Clone()
env.Prepend(LIBS=[rose_lib])

reader_bin = env.Program(target='reader',
                         source=[Glob('*.c')])

Return('reader_bin')

# vim:ft=python
