ERROR_DESC (R_ERR_GRP_COMPILE,
            R_ERR_BAD_FORMALS,
            "bad formals ~s n ~s")

ERROR_DESC (R_ERR_GRP_COMPILE,
            R_ERR_BAD_SYNTAX,
            "bad syntax ~s")

ERROR_DESC (R_ERR_GRP_COMPILE,
            R_ERR_BAD_VARIABLE,
            "bad variable ~s in ~s")

ERROR_DESC (R_ERR_GRP_RUNTIME,
            R_ERR_OOM,
            "out of memory")

ERROR_DESC (R_ERR_GRP_RUNTIME,
            R_ERR_INDEX_OVERFLOW,
            "index overflow")

ERROR_DESC (R_ERR_GRP_RUNTIME,
            R_ERR_UNBOUND_VAR,
            "variable ~s unbound")
ERROR_DESC (R_ERR_GRP_RUNTIME,
            R_ERR_UNKNOWN_INSTR,
            "unknown instruction ~s")

ERROR_DESC (R_ERR_GRP_RUNTIME,
            R_ERR_WRONG_APPLY,
            "wrong type to apply: ~s")

ERROR_DESC (R_ERR_GRP_RUNTIME,
            R_ERR_WRONG_ARG_NUM,
            "wrong number of arguments")

ERROR_DESC (R_ERR_GRP_RUNTIME,
            R_ERR_WRONG_TYPE_ARG,
            "wrong type argument ~s")

ERROR_DESC (R_ERR_GRP_RUNTIME,
            R_ERR_DIV_BY_ZERO,
            "division by zero")

ERROR_DESC (R_ERR_GRP_MISC,
            R_ERR_NOT_IMPLEMENTED,
            "~s is not implemented yet")

ERROR_DESC (R_ERR_GRP_MISC,
            R_ERR_UNKNOWN,
            "unknown error")

/* End mark */
ERROR_DESC (-1, R_ERR_END, NULL)
